FROM apache/airflow:latest

USER root

RUN apt-get update && \

    apt-get -y install git && \

    apt-get clean

USER airflow


# Install Jupyter and Python kernel
RUN pip install --no-cache-dir \
    jupyter \
    ipykernel \
    papermill \
    tensorflow \
    requests

EXPOSE 8080