FROM apache/airflow:latest

USER root

RUN apt-get update && \

    apt-get -y install git && \

    apt-get clean

USER airflow

# Install required Python packages
RUN pip install --no-cache-dir \
    papermill \
    requests

EXPOSE 8080